Controllers/OgrenciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using OgrenciNotMVC.Models.EntityFramework;

namespace OgrenciNotMVC.Controllers
{
    public class OgrenciController : Controller
    {
        DbOkulMvcEntities db = new DbOkulMvcEntities();
        public ActionResult Index()
        {
            var ogreciler = db.OGRENCILER.ToList();
            return View(ogreciler);
        }

        [HttpGet]
        public ActionResult YeniOgrenci()
        {
            List<SelectListItem> items = (from i in db.KULUPLER.ToList()
                                          select new SelectListItem
                                          {
                                              Text = i.KULUPAD,
                                              Value = i.KULUPID.ToString()
                                          }).ToList();
            ViewBag.klp = items;
            return View();
        }

        [HttpPost]
        public ActionResult YeniOgrenci(OGRENCILER o)
        {
            var klp = db.KULUPLER.Where(m => m.KULUPID == o.KULUPLER.KULUPID).FirstOrDefault();
            o.KULUPLER = klp;
            db.OGRENCILER.Add(o);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Sil(int id)
        {
            var ogr = db.OGRENCILER.Find(id);
            db.OGRENCILER.Remove(ogr);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult OgrenciGetir(int id)
        {
            var ogr=db.OGRENCILER.Find(id);

            List<SelectListItem> items = (from i in db.KULUPLER.ToList()
                                          select new SelectListItem
                                          {
                                              Text = i.KULUPAD,
                                              Value = i.KULUPID.ToString()
                                          }).ToList();
            ViewBag.klp = items;

            return View("OgrenciGetir",ogr);
        }

        public ActionResult Guncelle(OGRENCILER o)
        {
           // var klp = db.KULUPLER.Where(m => m.KULUPID == o.KULUPLER.KULUPID).FirstOrDefault();
           // o.KULUPLER = klp;
            var ogr = db.OGRENCILER.Find(o.OGRID);
            ogr.OGRAD = o.OGRAD;
            ogr.OGRSOYAD = o.OGRSOYAD;
            ogr.OGRFOTO=o.OGRFOTO;
            ogr.OGRCINSIYET= o.OGRCINSIYET;
            ogr.OGRKULUP = o.KULUPLER.KULUPID;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Ogrenci/Index.cshtml
@using OgrenciNotMVC.Models.EntityFramework
@model List<OGRENCILER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Öğrenciler</h3>
<br />
<div style="margin-bottom:10px">
    <a href="/Ogrenci/YeniOgrenci" class="btn btn-primary">Öğrenci Ekle</a>
</div>
<table class="table table-bordered">
    <tr>
        <th>ÖĞRENCİ ID</th>
        <th>AD</th>
        <th>SOYAD</th>
        <th>CİNSİYET</th>
        <th>KULÜP</th>
        <th>FOTO</th>
        <th>İŞLEMLER</th>
    </tr>
    <tbody>
        @foreach (var ogrenci in Model)
        {
            <tr>
                <td>@ogrenci.OGRID</td>
                <td>@ogrenci.OGRAD</td>
                <td>@ogrenci.OGRSOYAD</td>
                <td>@ogrenci.OGRCINSIYET</td>
                <td>@ogrenci.KULUPLER.KULUPAD</td>
                <td>
                    <a href="@ogrenci.OGRFOTO" class="btn btn-success">Göster<i class="glyphicon glyphicon-link"></i></a>
                    
                </td>
                <td>
                    <a href="/Ogrenci/Sil/@ogrenci.OGRID" class="btn btn-danger">Sil</a>
                    <a href="/Ogrenci/OgrenciGetir/@ogrenci.OGRID" class="btn btn-warning">Güncelle</a>
                </td>
            </tr>
        }

    </tbody>
</table>

Views/Ogrenci/OgrenciGetir.cshtml
@model OgrenciNotMVC.Models.EntityFramework.OGRENCILER
@{
    ViewBag.Title = "OgrenciGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Öğrenci Güncelle</h3>
<br />

@using (Html.BeginForm("Guncelle", "Ogrenci", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.OGRAD)
        @Html.TextBoxFor(m => m.OGRAD, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.OGRSOYAD)
        @Html.TextBoxFor(m => m.OGRSOYAD, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.OGRCINSIYET)
        @Html.TextBoxFor(m => m.OGRCINSIYET, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.OGRKULUP)
        @Html.DropDownListFor(m => m.KULUPLER.KULUPID, (List<SelectListItem>)ViewBag.klp, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.OGRFOTO)
        @Html.TextBoxFor(m => m.OGRFOTO, new { @class = "form-control" })
    </div>
    @Html.HiddenFor(m => m.OGRID)
    <div style="margin-top:15px">
        <button class="btn btn-primary">Güncelle</button>
    </div>
}

Views/Ogrenci/YeniOgrenci.cshtml
@model OgrenciNotMVC.Models.EntityFramework.OGRENCILER
@{
    ViewBag.Title = "YeniOgrenci";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" class="form-group">
    <div>
        <label>Öğrenci Adı</label>
        <input type="text" class="form-control" name="OGRAD" />
    </div>
    <div style="margin-top:10px">
        <label>Öğrenci Soyadı</label>
        <input type="text" class="form-control" name="OGRSOYAD" />
    </div>
    <div style="margin-top:10px">
        <label>Öğrenci Cinsiyeti</label>
        <input type="text" class="form-control" name="OGRCINSIYET" />
    </div>
    <div style="margin-top:10px">
        <label>Öğrenci Kulüp</label>
        @Html.DropDownListFor(m => m.KULUPLER.KULUPID, (List<SelectListItem>)ViewBag.klp, new { @class = "form-control" })
    </div>
    <div style="margin-top:10px">
        <label>Öğrenci Fotoğrafı</label>
        <input type="text" class="form-control" name="OGRFOTO" />
    </div>
    <div style="margin-top:10px">
        <button class="btn btn-info">Ekle</button>
    </div>
</form>