Controllers/KulupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OgrenciNotMVC.Models.EntityFramework;

namespace OgrenciNotMVC.Controllers
{
    public class KulupController : Controller
    {
        DbOkulMvcEntities db=new DbOkulMvcEntities();
        public ActionResult Index()
        {
            var kulupler = db.KULUPLER.ToList();
            return View(kulupler);
        }

        [HttpGet]
        public ActionResult YeniKulup()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniKulup(KULUPLER k)
        {
            db.KULUPLER.Add(k);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Sil(int id)
        {
            var kulup = db.KULUPLER.Find(id);
            db.KULUPLER.Remove(kulup);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KulupGetir(int id)
        {
            var kulup = db.KULUPLER.Find(id);
            return View("KulupGetir", kulup);
        }

        public ActionResult Guncelle(KULUPLER k)
        {
            var klp=db.KULUPLER.Find(k.KULUPID);
            klp.KULUPAD = k.KULUPAD;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Kulup/Index.cshtml
@using OgrenciNotMVC.Models.EntityFramework
@model List<KULUPLER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Kulüpler</h3>
<br />
<div style="margin-bottom:10px">
    <a href="/Kulup/YeniKulup" class="btn btn-primary">Kulüp Ekle</a>
</div>
<div class="wrapper">

    <table class="table table-bordered">
        <tr>
            <th>KULÜP ID</th>
            <th>KULÜP ADI</th>
            <th>KONTENJAN</th>
            <th>İŞLEMLER</th>
        </tr>
        <tbody>
            @foreach (var klp in Model)
            {
                <tr>
                    <td>@klp.KULUPID</td>
                    <td>@klp.KULUPAD</td>
                    <td>@klp.KONTENJAN</td>
                    <td><a href="/Kulup/Sil/@klp.KULUPID" class="btn btn-danger">Sil</a>
                        <a href="/Kulup/KulupGetir/@klp.KULUPID" class="btn btn-warning">Güncelle</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Kulup/KulupGetir.cshtml
@model OgrenciNotMVC.Models.EntityFramework.KULUPLER
@{
    ViewBag.Title = "KulupGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Kulüp Güncelle</h3>
<br />

@using (Html.BeginForm("Guncelle", "Kulup", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.KULUPAD)
        @Html.TextBoxFor(m => m.KULUPAD,new { @class="form-control" })
    </div>
    @Html.HiddenFor(m=>m.KULUPID)
    <div style="margin-top:15px">
        <button class="btn btn-primary">Güncelle</button>
    </div>
}

Views/Kulup/YeniKulup.cshtml
@{
    ViewBag.Title = "YeniKulup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" class="form-group">
    <div>
        <label>Kulüp Adı</label>
        <input type="text" class="form-control" name="KULUPAD" />
    </div>

    <div>
        <label>Kontenjan</label>
        <input type="text" class="form-control" name="KONTENJAN" />
    </div>

    <div style="margin-top:10px">
        <button class="btn btn-info">Ekle</button>
    </div>
</form>