Controllers/NotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OgrenciNotMVC.Models.EntityFramework;
using OgrenciNotMVC.Models;


namespace OgrenciNotMVC.Controllers
{
    public class NotController : Controller
    {
        DbOkulMvcEntities db=new DbOkulMvcEntities();
        public ActionResult Index()
        {
            var not = db.NOTLAR.ToList();
            return View(not);
        }

        [HttpGet]
        public ActionResult YeniSinav()
        {
            List<SelectListItem> items = (from i in db.DERSLER.ToList()
                                          select new SelectListItem
                                          {
                                              Text = i.DERSAD,
                                              Value = i.DERSID.ToString()
                                          }).ToList();
            ViewBag.drs = items;
            return View();
        }

        [HttpPost]
        public ActionResult YeniSinav(NOTLAR n)
        {
            var drs = db.DERSLER.Where(m => m.DERSID == n.DERSLER.DERSID).FirstOrDefault();
            n.DERSLER = drs;
            db.NOTLAR.Add(n);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult NotGetir(int id)
        {
            var not = db.NOTLAR.Find(id);
            return View("NotGetir",not);
        }

        [HttpPost]
        public ActionResult NotGetir(NOTLAR n,Class1 model, int sinav1=0,int sinav2=0,int sinav3=0,int proje=0)
        {
            if (model.islem == "HESAPLA")
            {
                int ortalama = (sinav1 + sinav2 + sinav3 + proje) / 4;
                ViewBag.ort = ortalama;
            }
            if (model.islem == "GUNCELLE")
            {
                var snv = db.NOTLAR.Find(n.NOTID);
                snv.SINAV1 = n.SINAV1;
                snv.SINAV2= n.SINAV2;
                snv.SINAV3= n.SINAV3;
                snv.PROJE = n.PROJE;
                snv.ORTALAMA = n.ORTALAMA;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Views/Not/Index.cshtml
@using OgrenciNotMVC.Models.EntityFramework
@model List<NOTLAR>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Notlar</h3>
<br />
<div style="margin-bottom:10px">
    <a href="/Not/YeniSinav" class="btn btn-primary">Sınav Not Girişi</a>
</div>
<table class="table table-bordered">
    <tr>
        <th>NOT ID</th>
        <th>DERS</th>
        <th>ÖĞRENCİ</th>
        <th>SINAV 1</th>
        <th>SINAV 2</th>
        <th>SINAV 3</th>
        <th>PROJE</th>
        <th>ORTALAMA</th>
        <th>DURUM</th>
        <th>İŞLEMLER</th>
    </tr>
    <tbody>
        @foreach (var not in Model)
        {
            <tr>
                <td>@not.NOTID</td>
                <td>@not.DERSLER.DERSAD</td>
                <td>@not.OGRENCILER.OGRAD</td>
                <td>@not.SINAV1</td>
                <td>@not.SINAV2</td>
                <td>@not.SINAV3</td>
                <td>@not.PROJE</td>
                <td>@not.ORTALAMA</td>
                <td>@not.DURUM</td>
                <td>
                    <a href="/Not/NotGetir/@not.NOTID" class="btn btn-warning">Güncelle</a>
                </td>
            </tr>
        }

    </tbody>
</table>

Views/Not/NotGetir.cshtml
@model OgrenciNotMVC.Models.EntityFramework.NOTLAR
@{
    ViewBag.Title = "NotGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Sınav Notu Güncelle</h3>
<br />

@using (Html.BeginForm("NotGetir", "Not", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.OGRID)
        @Html.TextBoxFor(m => m.OGRID, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.SINAV1)
        @Html.TextBoxFor(m => m.SINAV1, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.SINAV2)
        @Html.TextBoxFor(m => m.SINAV2, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.SINAV3)
        @Html.TextBoxFor(m => m.SINAV3, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.PROJE)
        @Html.TextBoxFor(m => m.PROJE, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ORTALAMA)
        @Html.TextBoxFor(m => m.ORTALAMA, new { @Value = @ViewBag.ort, @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.DURUM)
        @Html.TextBoxFor(m => m.DURUM, new { @class = "form-control" })
    </div>
    @Html.HiddenFor(m => m.NOTID)

    <div style="margin-top:15px">
        <button type="submit" name="islem" value="HESAPLA" class="btn btn-default">Hesapla</button>
    </div>

    <div style="margin-top:15px">
        <button type="submit" name="islem" value="GUNCELLE" class="btn btn-primary">Güncelle</button>
    </div>

}

Views/Not/YeniSinav.cshtml
@model OgrenciNotMVC.Models.EntityFramework.NOTLAR
@{
    ViewBag.Title = "YeniSinav";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" class="form-group">
    <div>
        <label>Öğrenci ID</label>
        <input type="text" class="form-control" name="OGRID" />
    </div>
    <div style="margin-top:10px">
        <label>Ders Adı</label>
        @Html.DropDownListFor(m => m.DERSLER.DERSID, (List<SelectListItem>)ViewBag.drs, new { @class = "form-control" })
    </div>
    <div style="margin-top:10px">
        <label>Sınav 1</label>
        <input type="text" class="form-control" name="SINAV1" />
    </div>
    <div style="margin-top:10px">
        <label>Sınav 2</label>
        <input type="text" class="form-control" name="SINAV2" />
    </div>
    <div style="margin-top:10px">
        <label>Sınav 3</label>
        <input type="text" class="form-control" name="SINAV3" />
    </div>
    <div style="margin-top:10px">
        <label>Proje</label>
        <input type="text" class="form-control" name="PROJE" />
    </div>
    <div style="margin-top:10px">
        <label>Ortalama</label>
        <input type="text" class="form-control" name="ORTALAMA" />
    </div>
    <div style="margin-top:10px">
        <label>Durum</label>
        <input type="text" class="form-control" name="DURUM" />
    </div>
    <div style="margin-top:10px">
        <button class="btn btn-info">Ekle</button>
    </div>
</form>